immich:
  persistence:
    library:
      existingClaim: immich-data

server:
  ingress:
    main:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
      hosts:
        - host: immich.triqster.eu
          paths:
            - path: "/"
              service:
                identifier: main
      tls:
      - hosts:
        - immich.triqster.eu
        secretName: immich-server-tls
